version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=true
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    volumes:
      - weather_data:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  weather_data:
